name: custom_position_popup
description: A new Flutter project.

 
 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

  
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# package
  animations: 
 
  flutter_lints: ^1.0.0

 
flutter:

 
  uses-material-design: true
 